feat: add model_max_length attribute and a warning
OSS-Pole-Emploi/gabarit pull request #132
Opened 2023-01-19 09:40 UTC by h4c5

## ✒️ Context

We encountered a problem with the `camembert/camembert-base` tokenizer while tokenizing large sequences.

This issue is caused by a flawed value of `tokenizer.model_max_length` which is set to `VERY_LARGE_NUMBER`.

This is probably an issue with the [`max_model_input_sizes`](https://huggingface.co/transformers/v4.0.1/main_classes/tokenizer.html?highlight=very_large_integer#transformers.PreTrainedTokenizer) attribute (dictionnary) of the pretrained tokenizer.
It should contain the model name : `camembert/camembert-base` but instead contains : `camembert-base` so [it
is not properly initialized](https://github.com/huggingface/transformers/blob/95f0dd21233297c8eb95d27d1f06150c54e6d8ab/src/transformers/tokenization_utils_base.py#L1926)

- What kind of change does this PR introduce ?

  - Bugfix
 
## 🧱 Description of Changes

- Add a `model_max_length` attribute in `ModelHuggingFace` class to let the user set the tokenizer attribute
- Add a warning when the model name is not in the `max_model_input_sizes` and `model_max_length` is set to `VERY_LARGE_NUMBER`

  - This is a change for the NLP template

## 🩺 Testing

- Manual test on the example of #123

## 🔗 References

- **Issue**: Closes #123

2023-01-19 10:15 UTC, gsolard approved these changes
Everything ok

2023-01-20 08:38 UTC, LexABzH requested changes
Several questions :
1. Are we sure this works on inference ? Using the `pipe` object.
2. model_max_length should be save in the configurations file, and manage in reload_from_standalone
3. unit tests should also test this new attribute

2023-01-20 16:53 UTC, LexABzH reviewed
Tested on inference, it works.

2023-01-20 16:53 UTC, LexABzH approved these changes

2023-01-20 16:54 UTC, merged