add super documents
OSS-Pole-Emploi/gabarit pull request #16
Opened 2022-07-20 15:12 UTC by eva24752460

add:

utils_super_documents (Method for the tfidf super documents)
model_tfidf_cos (Model for predictions TF-IDF Cosine Similarity)
model_tfidf_super_documents_naive (Model for predictions TF-IDF naive with super documents)

modify (add the option to use the 'super documents' method) :

model_tfidf_dense
model_tfidf_gbt
model_tfidf_lgbm
model_tfidf_sgdc
model_tfidf_svm

2022-07-21 13:22 UTC, LexABzH requested changes
- Lots of comments in files changes
- Functional tests must be added
- Train script must import new models
- 0_reload ... mus tbe updated to manage new models

2022-07-21 13:22 UTC, LexABzH commented on gabarit/template_nlp/nlp_project/package_name/models_training/model_tfidf_cos.py
> +            return self.compute_scores(x_test)
Not intuitive, 'scores' and return predictions ?

2022-07-21 13:22 UTC, LexABzH commented on gabarit/template_nlp/nlp_project/package_name/models_training/model_tfidf_cos.py
> +        self.matrix_train = self.matrix_train.astype(np.float16)
It should be done in fit, not in predict

2022-07-21 13:22 UTC, LexABzH commented on gabarit/template_nlp/nlp_project/package_name/models_training/model_tfidf_cos.py
> +            block_vec = vec[vec_row*chunk_size:(vec_row+1)*chunk_size]
pep8

2022-07-21 13:22 UTC, LexABzH commented on gabarit/template_nlp/nlp_project/package_name/models_training/model_tfidf_cos.py
> +                cosine = cosine_similarity(block_train, block_vec).astype(np.float16)
can probably be improved !

2022-07-21 13:22 UTC, LexABzH commented on gabarit/template_nlp/nlp_project/package_name/models_training/model_tfidf_super_documents_naive.py
> +            tfidf_transformer_params (dict): Parameters for the tfidf TfidfTransformer
fix kwargs order

2022-07-21 13:22 UTC, LexABzH commented on gabarit/template_nlp/nlp_project/package_name/models_training/model_tfidf_super_documents_naive.py
> +        self.matrix_train = csr_matrix((0,0))
Can probably be set to None

2022-07-21 13:22 UTC, LexABzH commented on gabarit/template_nlp/nlp_project/package_name/models_training/model_tfidf_super_documents_naive.py
> +        self.array_target = np.array([])
Can probably be set to None

2022-07-21 13:22 UTC, LexABzH commented on gabarit/template_nlp/nlp_project/package_name/models_training/model_tfidf_super_documents_naive.py
> +            if multiclass_strategy == 'ovr':
Change this to : ... in ['ovo', 'ovr']: ...

2022-07-21 13:22 UTC, LexABzH commented on gabarit/template_nlp/nlp_project/package_name/models_training/model_tfidf_super_documents_naive.py
> +    def save(self, json_data: Union[dict, None] = None) -> None:
Must be at the end of this file, check other classes

2022-07-21 13:22 UTC, LexABzH commented on gabarit/template_nlp/nlp_project/package_name/models_training/model_tfidf_super_documents_naive.py
> +        json_data['with_super_documents'] = self.with_super_documents
Not useful if already done in model_pipeline

2022-07-21 13:22 UTC, LexABzH commented on gabarit/template_nlp/nlp_project/package_name/models_training/model_tfidf_cos.py
> +        json_data['with_super_documents'] = self.with_super_documents
Not useful if already done in model_pipeline

2022-07-21 13:22 UTC, LexABzH commented on gabarit/template_nlp/nlp_project/package_name/models_training/model_tfidf_super_documents_naive.py
> +    def reload_from_standalone(self, **kwargs):
Must be at the end of this file, check other classes

2022-07-21 13:22 UTC, LexABzH commented on gabarit/template_nlp/nlp_project/package_name/models_training/model_tfidf_super_documents_naive.py
> +    '''Model for predictions via TF-IDF + Naive'''
Add more explanations ?

2022-07-21 13:22 UTC, LexABzH commented on gabarit/template_nlp/nlp_project/package_name/models_training/model_tfidf_super_documents_naive.py
> +            return self.compute_scores(x_test)
Not intuitive, 'scores' and return predictions ?

2022-07-21 13:22 UTC, LexABzH commented on gabarit/template_nlp/nlp_project/package_name/models_training/model_tfidf_super_documents_naive.py
> +    def compute_scores(self, x_test) -> np.ndarray:
Not intuitive, 'scores' and return predictions ?

2022-07-21 13:22 UTC, LexABzH commented on gabarit/template_nlp/nlp_project/package_name/models_training/model_tfidf_super_documents_naive.py
> +        - /!\\ THE MODEL NAIVE DOES NOT RETURN PROBABILITIES, HERE WE SIMULATE PROBABILITIES EQUAL TO 0 OR 1 /!\\ -
Can't this return a score ?

2022-07-21 13:22 UTC, LexABzH commented on gabarit/template_nlp/nlp_project/package_name/models_training/utils_super_documents.py
> +    def get_super_documents_count_vectorizer(self, x_train, y_train):
type hint ?

2022-07-21 13:22 UTC, LexABzH commented on gabarit/template_nlp/nlp_project/package_name/models_training/utils_super_documents.py
> +    '''TfidfTransformer for super documents'''
Add more explanations on super documents ?

2022-07-21 13:22 UTC, LexABzH commented on gabarit/template_nlp/nlp_project/package_name/models_training/utils_super_documents.py
> +        result = np.array([[sum(y) for y in x_train[x,:].transpose().toarray()] for x in index_array])
pep8

2022-07-21 13:22 UTC, LexABzH commented on gabarit/template_nlp/nlp_project/package_name/models_training/utils_super_documents.py
> +    def get_super_documents(self, x_train, y_train):
Type Hint

2022-07-21 13:22 UTC, LexABzH commented on gabarit/template_nlp/nlp_project/package_name/models_training/utils_super_documents.py
> +        super_train = df_train.groupby(y_train.name).agg({x_train.name:lambda sentence: ' '.join((sentence))})
pep8

2022-07-21 13:22 UTC, LexABzH commented on gabarit/template_nlp/nlp_project/package_name/models_training/utils_super_documents.py
> +    def fit(self, raw_documents, y=None):
type hint

2022-07-21 13:22 UTC, LexABzH commented on gabarit/template_nlp/nlp_project/package_name/models_training/utils_super_documents.py
> +    def fit_transform(self, raw_documents, y=None):
type hint

2022-07-21 13:22 UTC, LexABzH commented on gabarit/template_nlp/nlp_project/package_name/models_training/utils_super_documents.py
> +        return self.transform(raw_documents)
Add if __name__ == '__main__': .... error

2022-07-21 13:22 UTC, LexABzH commented on gabarit/template_nlp/nlp_project/package_name/models_training/utils_super_documents.py
> +    def fit_transform(self, raw_documents, y=None):
type hint

2022-07-21 13:33 UTC, gsolard commented on gabarit/template_nlp/nlp_project/package_name/models_training/model_pipeline.py
> +    def __init__(self, pipeline: Union[Pipeline, None] = None, with_super_documents: bool=False, **kwargs) -> None:
I agree. But then, one has to individually change each of the tfidf model. One solution would be to add a new class ModelTfidf wich is a child of ModelPipeline and a parent of all model_tfidf_... (except  model_tfidf_dense of course). So we do as you want:
1) change each individual model (but it is less practical to maintain)
2) add another class ModelTfidf (the best solution in my opinion)

2022-07-21 14:12 UTC, LexABzH commented on gabarit/template_nlp/nlp_project/package_name/models_training/model_pipeline.py
> +    def __init__(self, pipeline: Union[Pipeline, None] = None, with_super_documents: bool=False, **kwargs) -> None:
We can leave it like this for the moment. We'll see later if we have pipeline models without tfidf.

2022-09-27 13:16 UTC, LexABzH approved these changes

2022-11-10 15:58 UTC, closed without merging